<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * One invoice per hotel per billing month, generated by BillingService on the
 * 1st of each month. A hotel can prepay several months in advance via its
 * credit wallet (wallet_balance_cents on Hotel); the scheduler consumes the
 * wallet to settle this month's invoice automatically. An unpaid invoice is:
 *   overdue after the 5th, and its hotel gets suspended on the 6th.
 */
class MonthlyInvoice extends Model
{
    use HasFactory;

    public const STATUS_PENDING = 'pending';
    public const STATUS_PAID = 'paid';
    public const STATUS_OVERDUE = 'overdue';
    public const STATUS_SUSPENDED = 'suspended';
    public const STATUS_CANCELLED = 'cancelled';

    protected $table = 'monthly_invoices';

    protected $fillable = [
        'hotel_id',
        'subscription_plan_id',
        'hotel_subscription_id',
        'billing_month', // YYYY-MM
        'amount_cents',
        'paid_cents',
        'currency',
        'status',
        'payment_method', // wallet | cinetpay | manual
        'paid_at',
        'reference',
        'notes',
    ];

    protected $casts = [
        'amount_cents' => 'integer',
        'paid_cents' => 'integer',
        'billing_month' => 'string',
        'paid_at' => 'datetime',
    ];

    public function hotel(): BelongsTo
    {
        return $this->belongsTo(Hotel::class, 'hotel_id');
    }

    public function plan(): BelongsTo
    {
        return $this->belongsTo(SubscriptionPlan::class, 'subscription_plan_id');
    }

    public function subscription(): BelongsTo
    {
        return $this->belongsTo(HotelSubscription::class, 'hotel_subscription_id');
    }
}
